/**
 * This class is called whenever an ACTION is sent from a user.  E.g.
 * such events generated by typing "/me goes shopping" in most IRC clients.
 *  <p>
 * The implementation of this method in the PircBot abstract class
 * performs no actions and may be overridden as required.
 *
 * @param sender The nick of the user that sent the action.
 * @param login The login of the user that sent the action.
 * @param hostname The hostname of the user that sent the action.
 * @param target The target of the action, be it a channel or our nick.
 * @param action The action carried out by the user.
 */

package org.jibble.pircbot.handlers;

public class OnActionEventHandler extends AbstractEventHandler {

    public OnActionEventHandler(String sourceNick, String sourceLogin, String sourceHostname, String target, String substring){
        super.sourceNick=sourceNick;
        super.sourceLogin=sourceLogin;
        super.sourceHostname=sourceHostname;
        super.target=target;
        super.substring=substring;
    }
}
